name: parking_app
description: Simple Parking App with custom markers on Google Maps widgets
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  location: ^4.3.0
  moor_flutter: ^4.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.4.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/
